### ISSUE TITLE
Not usable on windows

### ISSUE THREAD

**Issue by Tapppi** [stevemao/mock-git#2]
Not usable on windows due to the use of shebangs and no shims.

**Comment by stevemao** [comment]
Sorry, can you provide more details?

**Comment by Tapppi** [comment]
~~Yeah sure:~~

~~1. windows searches the path for executables but if the exec doesn't have a file extension it searches for files with extensions from PATHEXT environment variable. Thus a mock file such as "git" is never found because when it is being searched Windows searches for "git.exe" "git.cmd" "git.bat" etc.~~
~~2. windows doesn't support shebangs so even if the command was magically found, it would not be executed as a node script.~~

~~The solution to both of these is to use cmd-shim. It's the same package npm uses to create the node_modules/.bin folder executables for windows. I'm just about to put up a pull request and will detail some caveats there.~~

This explanation belongs in stevemao/mock-bin, my bad, will follow up here shortly.

**Comment by Tapppi** [comment]
The issue in this repo was with backslashes not being escaped in the original git bin path before being passed to the JS mock. That prevented child_process.spawn from functioning correctly. #3 addresses this.
