### ISSUE TITLE
what does `t` mean in the readme's demo code

### ISSUE THREAD

**Issue by e-cloud** [stevemao/mock-git#8]

**Comment by stevemao** [comment]
Feel free to send a PR to fix it :)

**Comment by e-cloud** [comment]
The fact is i don't know what it means, then i can't fix it. :sweat: 

And it seems the demo inherits from [mock-bin](https://github.com/stevemao/mock-bin)

**Comment by Tapppi** [comment]
It's just an assertion. Basically means that the output (`actual`) is or is not equal to `log + '\n'`. Could probably be expressed better...

**Comment by stevemao** [comment]
@e-cloud does master look better? I hope the method names such as `is()` and `not()` should be pretty obvious what they are.
